# Generated by Django 3.0.5 on 2020-04-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200415_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
